version: '3.8'

services:
  api:
    build:
      context: ./app
    ports:
      - "5000:5000"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge
